title: Cool BRG
email: budhramgurung@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Gorkha | Freelance Full Stack Engineer | Trainer | Social Entrepreneur
  My name is Budh Ram Gurung. However, I preferred to be called as BRG.
  I am a FOSS Advocate and code for fun.
  I have gained most of my knowledge through self learning and follows Learn-Teach Cycle practice.
  Being involved in Open Source & its Culture was the best thing that happened in my professional career and
  believe that "Open Source is the Future".
baseurl: "" # the subpath of your site, e.g. /blog
thumbnail_path: "profile_pic.png"
url: "https://coolbrg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
future: true # Show blog post of future date

google_analytics: UA-133657720-1

paginate: 6
paginate_path: "/blogs/page:num"
permalink: /blogs/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jemoji

